# Generated by Django 5.2.1 on 2025-05-20 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
